# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath F:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.cache/wt} [current_project]
set_property parent.project_path {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files {{E:/Computer Organization/CPU54/54条指令CPU实验相关文档-2024/54条指令CPU实验相关文档/54条CPU_testbench+coe+results比对文件/mips_54_mars_simulate_student_ForWeb_2024.coe}}
add_files -quiet {{e:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{e:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp}}]
read_verilog -library xil_defaultlib {
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/Regfile.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/PC.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/MUX6_1.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/MUL.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/HI_LO.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/DIV.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/Decoder.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/CP0.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/ALU.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/DMEM.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/CPU.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/IMEM.v}
  {E:/Computer Organization/CPU54/54-single-CPU/54-single-CPU.srcs/sources_1/new/sccomp_dataflow.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
